class Worker{
    start()
    execute()
    stop()
    action()
}


class TelegramBot{
    init_user_chat()
    message_handler()
}

class Transaction{
    transaction_batch
    from
    to
    token
    transaction_time
}

class TransactionBatch{}

class TokensBag{
    user
    List[Token]
}

class User{

}

class Member{
    telegram_id
}

class Wallet{
    member
    currency
    amount
}


class Token{
    name
}

class Currency{}
class NFT{}

class SystemService{
    install()
}
class WinService{}
class LinuxService{}

SystemService <|-- WinService
SystemService <|-- LinuxService

Member <|-- User
Token <|-- Currency
Token <|-- NFT

Wallet -up-> Currency
Wallet -left-> Member
Transaction --> TransactionBatch
Transaction --> Currency

Wallet --|> TokensBag